name: Feature or new language
description: Suggest a feature, a challenge or a new fighter
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
  - type: checkboxes
    id: help
    attributes:
      label: Contributing
      options:
        - label: I'd like to implement this myself
